#!/bin/sh

DYNJS_MOD="-Dvertx.langs.dynjs=io.vertx~lang-dynjs~1.0.0-SNAPSHOT:org.dynjs.vertx.DynJSVerticleFactory"
JS_MAPPING="-Dvertx.langs..js=dynjs"

export JAVA_OPTS="$DYNJS_MOD $JS_MAPPING"

vertx run $*

